import binascii
import mmap

# Code Generated by chatgpt 3.5
def hex2byte(hex_string: str):
    return binascii.unhexlify(hex_string)

def hexpatch(file_path: str, from_hex: str, to_hex: str):
    patched = 1

    with open(file_path, 'r+b') as file:
        file_contents = mmap.mmap(file.fileno(), 0)

        pattern = hex2byte(from_hex)
        patch = hex2byte(to_hex)

        end = len(file_contents)
        curr = 0

        while curr < end:
            curr = file_contents.find(pattern, curr)
            if curr == -1:
                return patched

            print(f"Patch @ {curr:08X} [{from_hex}] -> [{to_hex}]")
            file_contents[curr:curr + len(pattern)] = b'\x00' * len(pattern)
            file_contents[curr:curr + len(patch)] = patch
            patched = 0

    return patched